# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/

# tasks:
#   - init: echo 'init script' # runs during prebuild
#     command: echo 'start script'
tasks:
  - name: Python API
    init: cd backend && pip install pipenv && pipenv install
    command: cd backend && export FLASK_APP=app && export FLASK_ENV=development && pipenv run python -m flask run`

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
