# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/

# tasks:
#   - init: echo 'init script' # runs during prebuild
#     command: echo 'start script'
tasks:
  - name: Python API
    init: >
      cd /workspace/camera_management/backend &&
        pip install pipenv &&
        pipenv install --system
    command: >
      cd /workspace/camera_management/backend && 
        pipenv install --system &&
        export FLASK_APP=app &&
        export FLASK_ENV=development &&
        python -m flask run

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
      