version: "3.8"

services:
  api_db_prod:
    container_name: api_db_prod
    image: postgres:13.8-alpine3.16
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
    networks:
      - prod

  ui_prod:
    container_name: ui_prod
    build: frontend/
    networks:
      - prod
    restart: unless-stopped

  api_prod:
    container_name: api_prod
    build: backend/
    command: sh -c "sleep 3s && pipenv install --system && python -m flask run --host=0.0.0.0"
    env_file:
      - .env
    depends_on:
      - api_db_prod
    networks:
      - prod
    restart: unless-stopped

  caddy:
    image: caddy:2.6.2-alpine
    restart: unless-stopped
    ports:
      - "4444:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data
    networks:
      - prod

networks:
  prod:
    name: network-for-prod
