version: "3.8"

services:
  # api_db:
  #   container_name: api_db
  #   image: postgres:latest
  #   ports:
  #     - "5432:5432"
  
  api:
    container_name: "api"
    build: .
    command: python -m flask run --host=0.0.0.0
    env_file:
      - .env
    volumes:
      - .:/backend
    ports:
      - "5000:5000"
    # depends_on:
    #  - api_db
    restart: unless-stopped

