version: "3.8"

services:
  api_db:
    container_name: api_db
    image: postgres:14.3-alpine3.16
    ports:
      - "5432:5432"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./db-data/:/var/lib/postgresql/data/

  api:
    container_name: "api"
    build: .
    command: python -m flask run --host=0.0.0.0
    env_file:
      - .env
    volumes:
      - .:/backend
    ports:
      - "8000:5000"
    depends_on:
     - api_db
    # restart: unless-stopped

