### Register
POST http://localhost:8000/api/register
Content-Type: application/json

{
	"email": "user4@test.com",
	"password": "password4",
	"first_name": "user4",
	"last_name": "last4"
}

### Login
POST http://localhost:8000/api/login
Content-Type: application/json

{
	"email": "user4@test.com",
	"password": "password4"
}

### Logout
POST http://localhost:8000/api/logout

### Test protected
GET http://localhost:8000/api/protected
