### Register
POST http://localhost:8000/api/register
Content-Type: application/json

{
	"email": "user4@test.com",
	"password": "password4",
	"first_name": "user4",
	"last_name": "last4"
}

### Login
POST http://localhost:8000/api/login
Content-Type: application/json

{
	"email": "user4@test.com",
	"password": "password4"
}

### Logout
POST http://localhost:8000/api/logout

### Test protected
GET http://localhost:8000/api/protected

### Insert mount
POST http://localhost:8000/api/mounts/add
Content-Type: application/json

{
	"id": 1,
	"name": "Canon-A"
}

### Get mounts
GET http://localhost:8000/api/mounts

### Insert item
POST http://localhost:8000/api/items/add
Content-Type: application/json

{
	"id": 1,
	"name": "Canon XD4",
	"image_url": "google.com",
	"stock": 12,
	"is_consumable": false,
	"is_lens": false,
	"mount_id": 1,
	"release": "2020/02/02"
}

### Get items
GET http://localhost:8000/api/items