### Insert mount
POST http://localhost:8000/api/mounts/add
Content-Type: application/json

{
	"name": "Canon-A"
}

### Insert mount 2
POST http://localhost:8000/api/mounts/add
Content-Type: application/json

{
	"name": "Sony AE"
}

### Insert mount 3
POST http://localhost:8000/api/mounts/add
Content-Type: application/json

{
	"name": "Delete me"
}


### Delete mount
POST http://localhost:8000/api/mounts/delete
Content-Type: application/json

{
	"id": 4
}

### Get mounts
GET http://localhost:8000/api/mounts

### Insert item
POST http://localhost:8000/api/items/add
Content-Type: application/json

{
	"name": "デジタル一眼カメラ α7 III",
	"image_url": "https://www.sony.jp/products/picture/ILCE-7M3K.jpg",
	"description": "一眼カメラメーカーの中でも近年急成長を見せているソニー。 キヤノンやニコンが中心となって展開していた一眼レフ全盛の時代からソニーはミラーレス一眼カメラの開発に力を入れていました。 そして最近になってミラーレス一眼カメラの存在価値が世間に認知されたことでソニーの一眼カメラというのはこれまで以上に注目を集める存在へと進化しました。 今回はそんなソニーが展開するミラーレス一眼カメラの中でもフルサイズセンサーを搭載し、代表的存在として人気を集めているα7IIIの魅力を作例とともにご紹介していきます。",
	"stock": 1,
	"is_consumable": false,
	"is_lens": false,
	"mount_id": 2,
	"release": "2020/02/02"
}

### Insert item 2
POST http://localhost:8000/api/items/add
Content-Type: application/json

{
	"name": "Sony a6400",
	"image_url": "sony.com",
	"stock": 1,
	"is_consumable": false,
	"is_lens": false,
	"mount_id": 2,
	"release": "2020/02/02"
}

### Insert item 3
POST http://localhost:8000/api/items/add
Content-Type: application/json

{
	"name": "Delete me",
	"image_url": "example.com",
	"stock": 1,
	"is_consumable": false,
	"is_lens": false,
	"mount_id": 2,
	"release": "2020/02/02"
}

### Delete item

POST http://localhost:8000/api/items/delete
Content-Type: application/json

{
	"id": 1
}

### Get items
GET http://localhost:8000/api/items
